In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.datasets import load_boston
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_wine

In [9]:
data=load_wine()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['Target']=data.target
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,Target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [15]:
df['Target'].value_counts()

1    71
0    59
2    48
Name: Target, dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB

In [8]:
df.duplicated().sum()

0

In [11]:
X=df.drop(columns=['Target'],axis=1)
y=df[['Target']]

In [12]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=1)

### Mutual Info Gain for Classification Problem

In [17]:
from sklearn.feature_selection import mutual_info_classif
# Determine the mutual information 
mutual_info=mutual_info_classif(X_train,y_train)
mutual_info

array([0.40973212, 0.30329003, 0.08648625, 0.23979627, 0.17334185,
       0.47348591, 0.6597241 , 0.09608948, 0.21918403, 0.54092784,
       0.46278457, 0.49478864, 0.59719855])

In [32]:
mutual_info=pd.Series(mutual_info)
mutual_info.index=X_train.columns
mutual_info.sort_values(ascending=False)

flavanoids                      0.659724
proline                         0.597199
color_intensity                 0.540928
od280/od315_of_diluted_wines    0.494789
total_phenols                   0.473486
hue                             0.462785
alcohol                         0.409732
malic_acid                      0.303290
alcalinity_of_ash               0.239796
proanthocyanins                 0.219184
magnesium                       0.173342
nonflavanoid_phenols            0.096089
ash                             0.086486
dtype: float64

In [34]:
from sklearn.feature_selection import SelectKBest

sel_five_cols=SelectKBest(mutual_info_classif,k=5)
sel_five_cols.fit(X_train,y_train)
X_train.columns[sel_five_cols.get_support()]

Index(['flavanoids', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines',
       'proline'],
      dtype='object')

### Mutual Info Gain for Regression Problem

In [106]:
house_df=pd.read_csv('C:\\Users\\Dell\\Data Science\\CampusX Tutorial\\Feature Selection\\test.csv')
house_df_feature=pd.read_csv('C:\\Users\\Dell\\Data Science\\CampusX Tutorial\\Feature Selection\\sample_submission.csv')

house_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [107]:
(house_df.columns[house_df.dtypes=='object'])

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [108]:
house_df_int= [columns for columns in house_df 
               if columns not in house_df.columns[house_df.dtypes=='object']]
len(house_df_int)

37

In [109]:
house_df=house_df[house_df_int]
house_df.drop(columns=['Id'],inplace=True)
house_df

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,730.0,140,0,0,0,120,0,0,6,2010
1,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,312.0,393,36,0,0,0,0,12500,6,2010
2,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,482.0,212,34,0,0,0,0,0,3,2010
3,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,470.0,360,36,0,0,0,0,0,6,2010
4,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,506.0,0,82,0,0,144,0,0,1,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,6,2006
1455,160,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,...,286.0,0,24,0,0,0,0,0,4,2006
1456,20,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,...,576.0,474,0,0,0,0,0,0,9,2006
1457,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,0.0,80,32,0,0,0,0,700,7,2006
1458,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,650.0,190,48,0,0,0,0,0,11,2006

In [110]:
house_df['SalesPrice']=house_df_feature['SalePrice']

In [111]:
X=house_df.drop(columns=['SalesPrice'],axis=1)
y=house_df[['SalesPrice']]

In [129]:
X.fillna(0,inplace=True)

In [130]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=1)

In [131]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1167, 36), (292, 36), (1167, 1), (292, 1))

In [132]:
from sklearn.feature_selection import mutual_info_regression

mutual_info= mutual_info_regression(X_train.fillna(0),y_train)

In [133]:
mutual_info=pd.Series(mutual_info)
mutual_info.index=X_train.columns
mutual_info.sort_values(ascending=False)

BedroomAbvGr     0.644442
LotArea          0.444399
TotRmsAbvGrd     0.320212
MSSubClass       0.294108
GrLivArea        0.240846
LotFrontage      0.146097
2ndFlrSF         0.126385
TotalBsmtSF      0.088681
1stFlrSF         0.087134
FullBath         0.086110
GarageArea       0.072649
OverallQual      0.066820
WoodDeckSF       0.058183
MoSold           0.057945
GarageCars       0.051073
YearBuilt        0.046421
MasVnrArea       0.044706
HalfBath         0.035440
BsmtFinSF1       0.032641
BsmtUnfSF        0.029518
KitchenAbvGr     0.027841
OpenPorchSF      0.026463
GarageYrBlt      0.025063
BsmtFullBath     0.022793
YearRemodAdd     0.022341
OverallCond      0.016299
Fireplaces       0.015708
YrSold           0.015461
EnclosedPorch    0.009318
BsmtFinSF2       0.003984
ScreenPorch      0.003719
MiscVal          0.001437
BsmtHalfBath     0.000000
3SsnPorch        0.000000
PoolArea         0.000000
LowQualFinSF     0.000000
dtype: float64

In [137]:
from sklearn.feature_selection import SelectPercentile
select_top_col = SelectPercentile(mutual_info_regression,percentile=20)
select_top_col.fit(X_train,y_train)
X_train.columns[select_top_col.get_support()]

Index(['MSSubClass', 'LotFrontage', 'LotArea', '2ndFlrSF', 'GrLivArea',
       'BedroomAbvGr', 'TotRmsAbvGrd'],
      dtype='object')

### THE END